name: CI-GPU

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-gpu:
    runs-on: ubuntu-latest
    container: nvidia/cuda

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Git and Ccache
      run: |
        apt-get update
        apt-get install -y git ccache

    - name: Initialize submodules
      run: |
        git submodule update --init --recursive

    - name: Build
      run: |
        nvidia-smi
        mkdir build
        cd build
        cmake -DTEST=ON -DCUDA=ON ..
        make

    - name: Run tests
      run: ctest --output-on-failure -C Debug -T test
      working-directory: build