name: CI-GPU

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-gpu:
    runs-on: ubuntu-latest
    container: 
        image: nvidia/cuda:12.6.0-base-ubuntu22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Ccache
      run: |
        apt-get update
        apt-get install -y ccache

    - name: Build
      run: |
        nvidia-smi
        mkdir build
        cd build
        cmake -DTEST=ON -DCUDA=ON ..
        make

    - name: Run tests
      run: ctest --output-on-failure -C Debug -T test
      working-directory: build